---
provider: BEW
url: "https://www.bergische-energie.de/dienstleistungen/elektromobilitaet/lokalstrom-mobil/"
tariffs:
- name: Lokalstrom mobil
  charge_card_id: 6
  monthly_fee: 1.66
  prices:
  - restrictions: []
    decomposition:
    - type: linear
      dimension: kwh
      price: 0.2999
      range:
      - 0
      - 50
    - type: linear
      dimension: kwh
      price: 0.2799
      range:
      - 50
      - 250
    - type: linear
      dimension: kwh
      price: 0.2499
      range:
      - 250
      - 