---
provider: EnBW
url: "https://www.enbw.com/elektromobilitaet/produkte/mobilityplus-app/laden-und-bezahlen"
tariffs:
- name: Standard
  charge_card_id: 319
  prices:
  - restrictions:
    - type: connector_energy
      value: ac
    decomposition:
    - type: linear
      dimension: kwh
      price: 0.39
  - restrictions:
    - type: connector_energy
      value: dc
    decomposition:
    - type: linear
      dimension: kwh
      price: 0.49
- name: Viellader
  charge_card_id: 319
  monthly_fee: 4.99
  prices:
  - restrictions:
    - type: connector_energy
      value: ac
    decomposition:
    - type: linear
      dimension: kwh
      price: 0.29
  - restrictions:
    - type: connector_energy
      value: dc
    decomposition:
    - type: linear
      dimension: kwh
      price: 0.39