---
provider: Energie Steiermark
url: "https://www.e-steiermark.com/privat/leistungen/elektromobilitaet/"
tariffs:
- name: easyFLEX
  charge_card_id: 276
  prices:
  - restrictions:
    - type: connector_speed
      value:
      - 3.7
      - 11
    decomposition:
    - type: linear
      price: 0.04
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 22
    decomposition:
    - type: linear
      price: 0.14
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 43
      - 50
    decomposition:
    - type: linear
      price: 0.44
      dimension: minute
- name: superFLAT
  charge_card_id: 276
  monthly_fee: 27.9
  flat_rate: true
  provider_customer_only: true
  prices:
  - restrictions:
    - type: connector_speed
      value:
      - 3.7
      - 11
      - 22
    decomposition:
    - type: constant
      price: 0
- name: superFLAT
  charge_card_id: 276
  monthly_fee: 29.9
  flat_rate: true
  prices:
  - restrictions:
    - type: connector_speed
      value:
      - 3.7
      - 11
      - 22
    decomposition:
    - type: constant
      price: 0
- name: powerFLAT
  charge_card_id: 276
  monthly_fee: 44.9
  flat_rate: true
  provider_customer_only: true
  prices:
  - restrictions: []
    decomposition:
    - type: constant
      price: 0
- name: powerFLAT
  charge_card_id: 276
  monthly_fee: 49.9
  flat_rate: true
  prices:
  - decomposition:
    - type: constant
      price: 0
