---
provider: Maingau Energie
url: "https://www.maingau-energie.de/e-mobilit%C3%A4t/autostrom-tarif"
tariffs:
- name: EinfachStromLaden
  charge_card_id: 274
  provider_customer_only: true
  prices:
  - restrictions:
    - type: connector_energy
      value: ac
    decomposition:
    - type: linear
      price: 0.15
      dimension: kwh
    - type: linear
      price: 0.1
      dimension: minute
      range:
      - 120
      - 
  - restrictions:
    - type: connector_energy
      value: dc
    decomposition:
    - type: linear
      price: 0.15
      dimension: kwh
    - type: linear
      price: 0.1
      dimension: minute
      range:
      - 120
      - 
- name: EinfachStromLaden
  charge_card_id: 274
  prices:
  - restrictions:
    - type: connector_energy
      value: ac
    - type: region
      value:
      - de
      - ch
    decomposition:
    - type: linear
      price: 0.25
      dimension: kwh
    - type: linear
      price: 0.1
      dimension: minute
      range:
      - 120
      - 
  - restrictions:
    - type: connector_energy
      value: dc
    - type: region
      value:
      - de
      - ch
    decomposition:
    - type: linear
      price: 0.25
      dimension: kwh
    - type: linear
      price: 0.1
      dimension: minute
      range:
      - 60
      - 
  - restrictions:
    - type: connector_energy
      value: ac
    - type: region
      value:
      - nl
    decomposition:
    - type: linear
      price: 0.3
      dimension: kwh
    - type: linear
      price: 0.1
      dimension: minute
      range:
      - 120
      - 
  - restrictions:
    - type: connector_energy
      value: dc
    - type: region
      value:
      - nl
    decomposition:
    - type: linear
      price: 0.3
      dimension: kwh
    - type: linear
      price: 0.1
      dimension: minute
      range:
      - 60
      - 
  - restrictions:
    - type: connector_energy
      value: ac
    - type: region
      value:
      - at
    decomposition:
    - type: linear
      price: 0.4
      dimension: kwh
    - type: linear
      price: 0.1
      dimension: minute
      range:
      - 120
      - 
  - restrictions:
    - type: connector_energy
      value: dc
    - type: region
      value:
      - at
    decomposition:
    - type: linear
      price: 0.4
      dimension: kwh
    - type: linear
      price: 0.1
      dimension: minute
      range:
      - 60
      - 
