---
provider: Smatrics
url: "https://ella.at/e3-ella-lohnt-sich/"
tariffs:
- name: Single Net
  charge_card_id: 156
  prices:
  - restrictions:
    - type: connector_speed
      value:
      - 3.7
      - 11
    decomposition:
    - type: linear
      price: 0.04
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 22
    - type: car_ac_phases
      value: 1
    decomposition:
    - type: linear
      price: 0.04
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 22
    - type: car_ac_phases
      value: 3
    decomposition:
    - type: linear
      price: 0.15
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 43
      - 50
    decomposition:
    - type: linear
      price: 0.45
      dimension: minute
- name: Smart Net
  charge_card_id: 157
  monthly_fee: 14.9
  prices:
  - restrictions:
    - type: connector_speed
      value:
      - 3.7
      - 11
    decomposition:
    - type: linear
      price: 0.02
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 22
    - type: car_ac_phases
      value: 1
    decomposition:
    - type: linear
      price: 0.02
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 22
    - type: car_ac_phases
      value: 3
    decomposition:
    - type: linear
      price: 0.04
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 43
      - 50
    decomposition:
    - type: linear
      price: 0.2
      dimension: minute
- name: Active Net
  charge_card_id: 158
  monthly_fee: 49.9
  prices:
  - restrictions:
    - type: connector_speed
      value:
      - 3.7
      - 11
    decomposition:
    - type: linear
      price: 0.01
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 22
    - type: car_ac_phases
      value: 1
    decomposition:
    - type: linear
      price: 0.01
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 22
    - type: car_ac_phases
      value: 3
    decomposition:
    - type: linear
      price: 0.03
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 43
      - 50
    decomposition:
    - type: linear
      price: 0.07
      dimension: minute