---
provider: VKW
url: "https://www.vlotte.at/produkte.htm"
tariffs:
- name: VLOTTE Public Flatrate
  charge_card_id: 268
  monthly_fee: 29.9
  flat_rate: true
  yearly_service_fee: 24
  provider_customer_only: true
  prices:
  - restrictions:
    - type: connector_speed
      value:
      - 3.7
    - type: connector_energy
      value: ac
    decomposition:
    - type: constant
      price: 0
    - type: linear
      price: 0.04
      dimension: minute
	  range:
	  - 180
	  - 
  - restrictions:
    - type: connector_speed
      value:
      - 11
      - 22
    - type: connector_energy
      value: ac
    decomposition:
    - type: constant
      price: 0
    - type: linear
      price: 0.11
      dimension: minute
	  range:
	  - 180
	  - 
  - restrictions:
    - type: connector_speed
      value:
      - 43
    - type: connector_energy
      value: ac
    decomposition:
    - type: constant
      price: 0
    - type: linear
      price: 0.30
      dimension: minute
	  range:
	  - 45
	  - 
  - restrictions:
    - type: connector_speed
      value:
      - 50
    - type: connector_energy
      value: dc
    decomposition:
    - type: constant
      price: 0
    - type: linear
      price: 0.30
      dimension: minute
	  range:
	  - 45
	  - 
- name: VLOTTE Public Flatrate
  charge_card_id: 268
  monthly_fee: 29.9
  flat_rate: true
  yearly_service_fee: 84
  prices:
  - restrictions:
    - type: connector_speed
      value:
      - 3.7
    - type: connector_energy
      value: ac
    decomposition:
    - type: constant
      price: 0
    - type: linear
      price: 0.04
      dimension: minute
	  range:
	  - 180
	  - 
  - restrictions:
    - type: connector_speed
      value:
      - 11
      - 22
    - type: connector_energy
      value: ac
    decomposition:
    - type: constant
      price: 0
    - type: linear
      price: 0.11
      dimension: minute
	  range:
	  - 180
	  - 
  - restrictions:
    - type: connector_speed
      value:
      - 43
    - type: connector_energy
      value: ac
    decomposition:
    - type: constant
      price: 0
    - type: linear
      price: 0.30
      dimension: minute
	  range:
	  - 45
	  - 
  - restrictions:
    - type: connector_speed
      value:
      - 50
    - type: connector_energy
      value: dc
    decomposition:
    - type: constant
      price: 0
    - type: linear
      price: 0.30
      dimension: minute
	  range:
	  - 45
	  - 
- name: VLOTTE Public PayPerUse
  charge_card_id: 83
  provider_customer_only: true
  yearly_service_fee: 24
  prices:
  - restrictions:
    - type: connector_speed
      value:
      - 3.7
    - type: connector_energy
      value: ac
    decomposition:
    - type: linear
      price: 0.04
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 11
	  - 22
    - type: connector_energy
      value: ac
    decomposition:
    - type: linear
      price: 0.11
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
	  - 43
    - type: connector_energy
      value: ac
    decomposition:
    - type: linear
      price: 0.30
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
	  - 50
    - type: connector_energy
      value: dc
    decomposition:
    - type: linear
      price: 0.30
      dimension: minute
- name: VLOTTE Public PayPerUse
  charge_card_id: 83
  yearly_service_fee: 84
  prices:
  - restrictions:
    - type: connector_speed
      value:
      - 3.7
    - type: connector_energy
      value: ac
    decomposition:
    - type: linear
      price: 0.04
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
      - 11
	  - 22
    - type: connector_energy
      value: ac
    decomposition:
    - type: linear
      price: 0.11
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
	  - 43
    - type: connector_energy
      value: ac
    decomposition:
    - type: linear
      price: 0.30
      dimension: minute
  - restrictions:
    - type: connector_speed
      value:
	  - 50
    - type: connector_energy
      value: dc
    decomposition:
    - type: linear
      price: 0.30
      dimension: minute
